### Crear evento
POST http://localhost:3000/events
Content-Type: application/json

{
  "nombre": "Programacion basica",
  "descripcion": " tecnología",
  "ubicacion": "Lima ",
  "fechaEvento": "2026-08-04",
  "capacidad": 200
}

### Listar eventos
GET http://localhost:3000/events

### Obtener evento por ID
GET http://localhost:3000/events/10

### Actualizar evento
PUT http://localhost:3000/events/8
Content-Type: application/json

{
  "nombre": "Progamacion Avanzada",
  "descripcion": "Conferencia",
  "ubicacion": "Lima",
  "fechaEvento": "2027-07-04",
  "capacidad": 2
}
### Eliminar evento
DELETE http://localhost:3000/events/10

### Registrar inscripción
POST http://localhost:3000/registrations
Content-Type: application/json

{
  "participante": "miguel ",
  "correo": "francisbazan707@mail.com",
  "telefono": "999888777",
  "eventoId": 8
}

### Listar inscripciones
GET http://localhost:3000/registrations

### Inscripciones por evento
GET http://localhost:3000/registrations/event/8

### Buscar por participante
GET http://localhost:3000/registrations/participant/Francis

### Cancelar inscripción
DELETE http://localhost:3000/registrations/5